import { Navbar } from '@/components/marketing/Navbar'
import { Footer } from '@/components/marketing/Footer'
import Link from 'next/link'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'AI Content Detector | Sovira AI',
  description: 'Instantly scan your text to see how likely it is to be flagged as AI-generated by search engines or clients. Ensure your content reads flawlessly human.',
}

export default function AiDetectorPage() {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#0A101F] font-sans selection:bg-rose-500/30">
      <Navbar />

      <main className="relative pt-24 pb-16 md:pt-32 md:pb-24 overflow-hidden">
        {/* Background glow */}
        <div className="absolute inset-0 z-0 bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-rose-100/50 via-slate-50 to-slate-50 dark:from-rose-900/20 dark:via-[#0A101F] dark:to-[#0A101F] pointer-events-none" />

        <div className="mx-auto max-w-4xl px-6 lg:px-8 relative z-10">
          <div className="text-center mb-16">
            <h1 className="text-4xl md:text-6xl font-extrabold text-slate-900 dark:text-white tracking-tight mb-6">
              Ensure Your Content Passes <span className="text-transparent bg-clip-text bg-gradient-to-r from-rose-600 to-rose-400">Every AI Check</span>
            </h1>
            <p className="text-xl text-slate-600 dark:text-slate-300 max-w-2xl mx-auto leading-relaxed">
              Instantly scan your text to see exactly how likely it is to be flagged as AI-generated by Turnitin, GPTZero, or Google's spam filters. Get an instant, clear signal before you hit publish.
            </p>
          </div>

          <div className="prose prose-slate dark:prose-invert prose-lg max-w-none prose-headings:font-extrabold prose-headings:tracking-tight prose-a:font-semibold prose-a:text-rose-600 dark:prose-a:text-rose-400 hover:prose-a:text-rose-500 bg-white dark:bg-[#111827] p-8 md:p-12 rounded-3xl shadow-xl ring-1 ring-slate-100 dark:ring-slate-800">
            <h2 className="mt-0">The Problem with Robotic Content</h2>
            <p>
              In an era of mass-produced AI content, authenticity is your biggest competitive advantage. Businesses and content creators face real risks when publishing text that reads as obviously AI-generated—ranging from devastating search-engine spam penalties to breaking trust with high-paying clients. If your writing feels automated, your audience will tune out, and search algorithms will devalue your pages.
            </p>

            <h3>Deep Pattern Analysis</h3>
            <p>
              The Sovira AI Detector doesn't just guess based on keywords. It dives deep into the underlying structure of your writing, analyzing perplexity (how predictable the word choices are) and burstiness (the variation in sentence length and structure) exactly like enterprise detection software does. 
            </p>

            <h3>Instant Peace of Mind</h3>
            <p>
              We've made the process completely frictionless. Just paste your text into the analyzer and receive a color-coded probability score alongside a plain-English reasoning report in seconds. It provides the quick gut-check you need to ensure your tone is authentic and engaging.
            </p>

            <h3>The Complete Quality Loop</h3>
            <p>
              Our detector is built to be part of a seamless editing workflow. If your content scores as too robotic or predictable, you don't have to spend hours manually rewriting it. With a single click, you can send the flagged text directly to our AI Humanizer, which restructures the phrasing to make it read more naturally, ensuring your final draft is both high-quality and undeniably human.
            </p>

            <h3>Ready to Publish with Confidence?</h3>
            <p>
              Don't let rigid, robotic phrasing ruin your search rankings or damage your client trust. Scan your content now and ensure every piece you publish reads flawlessly human. Head over to our <Link href="/pricing">pricing page</Link> to start your risk-free trial today.
            </p>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}
