import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { checkUsageLimit } from '@/lib/usage'

export async function POST(req: Request) {
  try {
    const { text } = await req.json()
    
    if (!text || text.trim().length < 50) {
      return NextResponse.json({ error: 'Text must be at least 50 characters long to analyze accurately.' }, { status: 400 })
    }

    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Checking usage (AI Words limit is a good proxy for general usage)
    const { limitReached, maxLimit } = await checkUsageLimit(user.id, 'words')
    if (limitReached) {
      return NextResponse.json({ error: `You have reached your AI usage limit (${maxLimit.toLocaleString()} words). Please upgrade your plan.` }, { status: 403 })
    }

    const systemPrompt = `You are an advanced AI Detection Engine. Your job is to analyze text and determine the probability (0 to 100) that it was generated by an AI (like ChatGPT, Claude, Gemini, etc.).
Analyze the text's perplexity, burstiness, structural uniformity, phrasing, and vocabulary choices.

You MUST return ONLY a valid JSON object with the following structure. Do not include markdown blocks like \`\`\`json. Return raw JSON.
{
  "score": number, // 0 to 100 (100 means definitely AI, 0 means definitely Human)
  "reasoning": "A short 1-2 sentence explanation focusing on perplexity, burstiness, or mechanical phrasing."
}`

    const prompt = `Analyze this text for AI generation:\n\n${text}`

    const apiKey = (process.env.NARA_API_KEY || 'sk-nry-6B9r9RkKfP3tjv7PGx8sLdq8z7x0htWoDVEuHsFy0rs').trim()
    if (!apiKey) {
      return NextResponse.json({ error: 'NARA_API_KEY is missing' }, { status: 500 })
    }
    
    const response = await fetch(`https://router.bynara.id/v1/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: 'mistral-large',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: prompt }
        ],
        temperature: 0.1,
        response_format: { type: 'json_object' }
      })
    })

    if (!response.ok) {
      const errorText = await response.text()
      throw new Error(`Nara API Error: ${response.status} - ${errorText}`)
    }

    const data = await response.json()
    const resultText = data.choices?.[0]?.message?.content
    
    if (!resultText) throw new Error('No content returned from Nara')

    let parsed
    try {
      parsed = JSON.parse(resultText)
    } catch (e) {
      // Fallback if the AI fails to return strict JSON
      parsed = {
        score: 50,
        reasoning: "Analysis failed due to a formatting error from the detection engine."
      }
    }

    const wordCount = text.trim().split(/\s+/).length

    // Log the AI usage
    await supabase.from('activity_logs').insert([{
      user_id: user.id,
      action: `AI Text Detection`, 
      details: { score: parsed.score, words: wordCount }
    }])

    return NextResponse.json(parsed)

  } catch (error: any) {
    console.error('AI Detector Error:', error)
    return NextResponse.json({ error: error.message || 'Failed to analyze text' }, { status: 500 })
  }
}
