import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#0F172A] text-slate-900 dark:text-white p-6 py-16 md:py-24">
      <div className="max-w-4xl mx-auto space-y-8">
        <Link href="/" className="inline-flex items-center gap-2 text-blue-600 dark:text-blue-400 font-semibold hover:underline mb-8">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>
        
        <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight">Privacy Policy</h1>
        <p className="text-slate-500">Last updated: {new Date().toLocaleDateString()}</p>
        
        <div className="prose prose-slate dark:prose-invert max-w-none space-y-6 text-slate-700 dark:text-slate-300">
          
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8">Abstract & API Services Data Policy</h2>
          <p>
            At Sovira SEO, we value your privacy and are committed to protecting your personal information. Our platform strictly adheres to the data protection policies of the APIs we integrate with, including the Google API Services User Data Policy and its Limited Use requirements.
          </p>
          <p>
            Our application's use and transfer of information received from Google APIs (such as Google PageSpeed Insights and Gemini) or other third-party APIs strictly align with their respective User Data Policies. 
          </p>

          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Website and tells You about Your privacy rights and how the law protects You. By using the Website, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8">Interpretation and Definitions</h2>
          <p><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Sovira SEO, operating under Dorvas Technologies.</p>
          <p><strong>Account</strong> means a unique account created for You to access our Website or parts of our Website.</p>
          <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
          <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Website or from the Website infrastructure itself.</p>

          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8">Collecting and Using Your Personal Data</h2>
          <p>While using Our Website, We may ask You to provide Us with certain personally identifiable information, including but not limited to:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Usage Data (IP address, browser type, pages visited)</li>
          </ul>

          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8">Exact API Services & Third-Party Integrations</h2>
          <p>We believe in full transparency regarding the infrastructure that powers Sovira SEO. We utilize the following specific API services:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>Supabase:</strong> Serves as our primary database and authentication provider. Your account details and stored SEO data are encrypted and securely hosted here.</li>
            <li><strong>Stripe & Paystack:</strong> Our secure payment processors. We do not store or collect your raw payment card details.</li>
            <li><strong>Apify:</strong> Utilized for real-time web scraping to power our Rank Tracking and Competitor Analysis features.</li>
            <li><strong>Google Gemini & Groq:</strong> Our core AI engines utilized for Content Generation, Keyword Research logic, and Audit analysis. Only necessary contextual data (like target URLs or keywords) is sent to these APIs to generate responses.</li>
            <li><strong>Google PageSpeed Insights API:</strong> Used to run technical performance audits on your submitted domains.</li>
          </ul>

          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8">Requesting Account & Data Deletion</h2>
          <p>We respect your right to privacy and provide every user with the ability to permanently delete their account and all personal information stored with Sovira SEO.</p>
          <p><strong>How to Submit a Deletion Request:</strong></p>
          <p>Send a WhatsApp message to our support line at <strong>+234 816 233 7303</strong> or email us with the subject line: "Account Deletion Request". Please include the email address associated with your account.</p>
          <p>Once we receive your request, we will verify your identity and permanently delete your account and all associated personal information from our active systems within 7 business days.</p>

          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8">Tracking Technologies and Cookies</h2>
          <p>We use Cookies and similar tracking technologies to track the activity on Our Website and store certain information. The technologies We use may include:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>Necessary / Essential Cookies:</strong> Essential to provide You with services available through the Website and to enable You to use some of its features.</li>
            <li><strong>Functionality Cookies:</strong> Allow us to remember choices You make when You use the Website, such as your authentication state.</li>
          </ul>

          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8">GDPR & CCPA Privacy Rights</h2>
          <p>If you are a resident of the European Economic Area (EEA) or California, you have specific data protection rights, including:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>The right to access, update or delete</strong> the information We have on You.</li>
            <li><strong>The right of rectification.</strong> You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
            <li><strong>The right to object.</strong> You have the right to object to our processing of your Personal Data.</li>
            <li><strong>The right of restriction.</strong> You have the right to request that we restrict the processing of your personal information.</li>
            <li><strong>The right to say no to the sale of Personal Data (CCPA).</strong> We do not sell your personal data.</li>
          </ul>

          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8">Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us via WhatsApp: <a href="https://wa.me/2348162337303" className="text-blue-600 dark:text-blue-400 hover:underline">+234 816 233 7303</a></p>

        </div>
      </div>
    </div>
  )
}
