'use client'

import { useState } from 'react'
import { Sparkles, FileText, ChevronDown, Paperclip, ArrowUp, ArrowLeft, Loader2, Download, MonitorPlay } from 'lucide-react'
import Link from 'next/link'
import toast from 'react-hot-toast'
import pptxgen from 'pptxgenjs'

const TEMPLATES = [
  { id: '1', title: 'Patient Safety Protocols', color: 'bg-blue-600' },
  { id: '2', title: 'Partnership Guide 2026', color: 'bg-slate-800' },
  { id: '3', title: 'Occupational Psychology', color: 'bg-teal-600' },
  { id: '4', title: 'Copywriting Essentials', color: 'bg-rose-100 text-rose-900' },
]

export default function SlidesAgentPage() {
  const [prompt, setPrompt] = useState('')
  const [slideCount, setSlideCount] = useState('5-10 Slides')
  const [isGenerating, setIsGenerating] = useState(false)
  const [showPreview, setShowPreview] = useState(false)
  const [activeTab, setActiveTab] = useState('Professional')
  const [selectedTemplate, setSelectedTemplate] = useState<string | null>(null)

  const handleGenerate = () => {
    if (!prompt.trim()) {
      toast.error('Please enter a presentation topic first.')
      return
    }
    setIsGenerating(true)
    // Mock AI generation delay
    setTimeout(() => {
      setIsGenerating(false)
      setShowPreview(true)
    }, 2500)
  }

  const exportPPTX = () => {
    toast.loading('Generating PowerPoint file...', { id: 'pptx' })
    
    try {
      // 1. Create a new Presentation
      let pres = new pptxgen()

      // 2. Add a Slide
      let slide1 = pres.addSlide()
      slide1.background = { color: 'FFFFFF' }
      slide1.addText(prompt || 'Generated Presentation', { x: 1, y: 2, w: '80%', fontSize: 36, bold: true, color: '363636' })
      slide1.addText('Generated by Sovira AI Slides Agent', { x: 1, y: 3, w: '80%', fontSize: 18, color: '666666' })

      let slide2 = pres.addSlide()
      slide2.addText('Key Points', { x: 0.5, y: 0.5, w: '90%', fontSize: 24, bold: true, color: '363636' })
      slide2.addText('• Point 1: Introduction\n• Point 2: Core Concepts\n• Point 3: Strategic Implementation\n• Point 4: Conclusion', { x: 0.5, y: 1.5, w: '90%', fontSize: 18, color: '363636', bullet: true })

      // 3. Save the Presentation
      pres.writeFile({ fileName: 'Sovira_Presentation.pptx' }).then(() => {
        toast.success('Downloaded successfully!', { id: 'pptx' })
        setShowPreview(false)
        setPrompt('')
      })
    } catch (e) {
      toast.error('Failed to generate PPTX', { id: 'pptx' })
    }
  }

  return (
    <div className="flex flex-col max-w-5xl mx-auto pb-20">
      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <Link href="/dashboard" className="flex items-center text-sm font-medium text-slate-500 hover:text-slate-900 dark:hover:text-white transition-colors">
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back
        </Link>
        <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Slides Agent</h1>
        <div className="flex items-center gap-2 bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-500 px-3 py-1.5 rounded-full text-xs font-semibold">
          <Sparkles className="w-3.5 h-3.5" />
          Go Pro from just $9/mo
        </div>
      </div>

      {/* Tabs */}
      <div className="flex justify-center mb-6">
        <div className="flex space-x-2 bg-slate-100 dark:bg-slate-800/50 p-1 rounded-full border border-slate-200 dark:border-slate-700/50">
          {['Professional', 'Creative', 'Beautify'].map(tab => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-6 py-2 text-sm font-medium rounded-full transition-all ${
                activeTab === tab 
                  ? 'bg-white dark:bg-slate-700 shadow-sm text-[#F97316] ring-1 ring-slate-200 dark:ring-slate-600' 
                  : 'text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
              }`}
            >
              {tab}
            </button>
          ))}
        </div>
      </div>

      {/* Input Box */}
      <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm border border-[#F97316]/30 dark:border-[#F97316]/50 overflow-hidden ring-4 ring-[#F97316]/5 transition-all focus-within:ring-[#F97316]/10">
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Enter your presentation topic, idea, or requirements..."
          className="w-full min-h-[120px] p-6 text-lg bg-transparent border-none outline-none resize-none placeholder:text-slate-400 text-slate-900 dark:text-white"
        />
        
        {/* Bottom Toolbar */}
        <div className="flex items-center justify-between px-4 py-3 bg-slate-50/50 dark:bg-slate-900/20 border-t border-slate-100 dark:border-slate-700/50">
          <div className="flex items-center gap-3">
            <button 
              onClick={handleGenerate}
              disabled={isGenerating}
              className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg transition-colors"
            >
              {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4 text-[#F97316]" />}
              Generate Agent
            </button>

            <div className="h-4 w-px bg-slate-200 dark:bg-slate-700"></div>

            <select 
              value={slideCount}
              onChange={(e) => setSlideCount(e.target.value)}
              className="bg-transparent text-sm font-medium text-slate-600 dark:text-slate-300 outline-none cursor-pointer appearance-none px-2 pr-6 relative"
            >
              <option>5-10 Slides</option>
              <option>10-15 Slides</option>
              <option>15-20 Slides</option>
            </select>

            <div className="h-4 w-px bg-slate-200 dark:bg-slate-700"></div>

            <select className="bg-transparent text-sm font-medium text-slate-600 dark:text-slate-300 outline-none cursor-pointer appearance-none px-2 pr-6">
              <option>16:9</option>
              <option>4:3</option>
            </select>
          </div>

          <div className="flex items-center gap-4">
            <span className="text-xs font-medium text-slate-400">25 Credits</span>
            <button className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 transition-colors">
              <Paperclip className="w-4 h-4" />
            </button>
            <button 
              onClick={handleGenerate}
              disabled={isGenerating}
              className="w-8 h-8 rounded-full bg-[#F97316] text-white flex items-center justify-center hover:bg-[#EA580C] transition-colors disabled:opacity-50"
            >
              <ArrowUp className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>

      {/* Templates Section */}
      <div className="mt-12">
        <div className="flex items-center gap-6 border-b border-slate-200 dark:border-slate-800 mb-6">
          <button className="text-sm font-bold text-slate-900 dark:text-white pb-3 border-b-2 border-[#F97316]">
            Recommend Templates
          </button>
          <button className="text-sm font-medium text-slate-500 hover:text-slate-900 dark:hover:text-white pb-3">
            My Templates
          </button>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="aspect-[16/9] rounded-xl border-2 border-dashed border-slate-200 dark:border-slate-700 flex flex-col items-center justify-center text-slate-500 cursor-pointer hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
            <span className="text-2xl mb-2">+</span>
            <span className="text-xs font-semibold">Click add your template</span>
          </div>
          
          {TEMPLATES.map((t) => (
            <div 
              key={t.id} 
              onClick={() => setSelectedTemplate(t.id)}
              className={`relative aspect-[16/9] rounded-xl overflow-hidden cursor-pointer group ring-1 ring-slate-200 dark:ring-slate-800 hover:ring-[#F97316] transition-all ${t.color}`}
            >
              <div className="absolute inset-0 bg-black/10 group-hover:bg-black/20 transition-colors" />
              <div className="absolute bottom-4 left-4 right-4">
                <h3 className="text-sm font-bold text-white shadow-sm leading-tight">{t.title}</h3>
              </div>
              {selectedTemplate === t.id && (
                <div className="absolute top-2 right-2 bg-[#F97316] text-white text-[10px] px-2 py-0.5 rounded-full font-bold">
                  Selected
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Preview Modal (Mocked) */}
      {showPreview && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-2xl max-w-4xl w-full overflow-hidden flex flex-col max-h-[90vh]">
            <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 dark:border-slate-800">
              <h3 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <MonitorPlay className="w-5 h-5 text-[#F97316]" />
                Slides Preview
              </h3>
              <button onClick={() => setShowPreview(false)} className="text-slate-400 hover:text-slate-600">
                ✕
              </button>
            </div>
            
            <div className="p-8 bg-slate-100 dark:bg-slate-950 flex-1 overflow-y-auto flex items-center justify-center">
              {/* Mock Slide Preview */}
              <div className="w-full max-w-2xl aspect-[16/9] bg-white rounded-lg shadow-md flex flex-col items-center justify-center p-12 text-center border-t-8 border-[#F97316]">
                <h2 className="text-3xl font-extrabold text-slate-800 mb-4">{prompt || 'Generated Presentation'}</h2>
                <p className="text-slate-500">Prepared exclusively by Sovira Slides Agent</p>
              </div>
            </div>

            <div className="px-6 py-4 border-t border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-900 flex justify-end gap-3">
              <button onClick={() => setShowPreview(false)} className="px-5 py-2 text-sm font-medium text-slate-600 hover:text-slate-900">
                Edit Outline
              </button>
              <button onClick={exportPPTX} className="flex items-center gap-2 px-6 py-2 bg-[#F97316] hover:bg-[#EA580C] text-white text-sm font-semibold rounded-lg shadow-md transition-colors">
                <Download className="w-4 h-4" />
                Export to PowerPoint
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
