'use client'

import { useState } from 'react'
import { Radar, Loader2, ShieldAlert, CheckCircle2, AlertTriangle, ShieldCheck, FileText, Info } from 'lucide-react'
import { toast } from 'react-hot-toast'
import Link from 'next/link'

export default function AIDetectorPage() {
  const [text, setText] = useState('')
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const [result, setResult] = useState<{ score: number; reasoning: string } | null>(null)

  const handleAnalyze = async () => {
    if (text.trim().length < 50) {
      toast.error('Please enter at least 50 characters for an accurate analysis.')
      return
    }

    setIsAnalyzing(true)
    setResult(null)

    try {
      const response = await fetch('/api/detect', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ text })
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || 'Failed to analyze text')
      }

      setResult({
        score: data.score,
        reasoning: data.reasoning
      })
      
    } catch (error: any) {
      toast.error(error.message)
    } finally {
      setIsAnalyzing(false)
    }
  }

  const getScoreColor = (score: number) => {
    if (score > 70) return 'text-red-500' // Highly likely AI
    if (score > 40) return 'text-yellow-500' // Mix or uncertain
    return 'text-green-500' // Human
  }

  const getScoreBg = (score: number) => {
    if (score > 70) return 'bg-red-500'
    if (score > 40) return 'bg-yellow-500'
    return 'bg-green-500'
  }

  const getScoreLabel = (score: number) => {
    if (score > 80) return 'AI Generated'
    if (score > 60) return 'Likely AI'
    if (score > 40) return 'Mixed / Uncertain'
    if (score > 20) return 'Likely Human'
    return 'Human Written'
  }

  const getScoreIcon = (score: number) => {
    if (score > 70) return <AlertTriangle className="w-12 h-12 text-red-500 mx-auto mb-4" />
    if (score > 40) return <ShieldAlert className="w-12 h-12 text-yellow-500 mx-auto mb-4" />
    return <CheckCircle2 className="w-12 h-12 text-green-500 mx-auto mb-4" />
  }

  return (
    <div className="max-w-7xl mx-auto space-y-8 animate-fade-in pb-20 lg:pb-0">
      
      {/* HEADER SECTION */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white dark:bg-slate-900 p-6 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm">
        <div className="flex items-center gap-4">
          <div className="p-3 bg-blue-100 dark:bg-blue-900/30 text-blue-600 rounded-xl">
            <Radar className="w-8 h-8" />
          </div>
          <div>
            <h1 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-slate-900 to-slate-700 dark:from-white dark:to-slate-300">
              AI Content Detector
            </h1>
            <p className="text-slate-500 dark:text-slate-400 mt-1">
              Check how likely your text is to be flagged as AI-generated by Turnitin or GPTZero.
            </p>
          </div>
        </div>
        <div className="flex items-center gap-3">
           <Link href="/humanizer" className="flex items-center gap-2 px-4 py-2 bg-emerald-50 text-emerald-600 dark:bg-emerald-900/20 dark:text-emerald-400 rounded-lg text-sm font-semibold border border-emerald-100 dark:border-emerald-800/30 hover:bg-emerald-100 dark:hover:bg-emerald-900/40 transition-colors">
              <ShieldCheck className="w-4 h-4" />
              Need to bypass detection? Use AI Humanizer
           </Link>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* LEFT COMPONENT: Input */}
        <div className="lg:col-span-2 bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden flex flex-col">
          <div className="border-b border-slate-100 dark:border-slate-800 p-4 bg-slate-50/50 dark:bg-slate-900/50 flex items-center justify-between">
            <div className="flex items-center gap-2 text-sm font-medium text-slate-700 dark:text-slate-300">
              <FileText className="w-4 h-4" />
              PASTE TEXT TO SCAN
            </div>
            <div className="text-xs text-slate-400 font-medium">
              {text.length > 0 ? `${text.trim().split(/\s+/).length} words` : '0 words'}
            </div>
          </div>
          
          <div className="p-4 flex-1">
            <textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder="Paste any text to check how likely it is to be flagged as AI-generated (minimum 50 characters)..."
              className="w-full h-96 lg:h-[500px] resize-none bg-transparent border-none focus:ring-0 text-slate-800 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-600 outline-none leading-relaxed"
            />
          </div>
          
          <div className="p-4 border-t border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-900/50 flex justify-between items-center">
            <button 
              onClick={() => setText('')}
              className="text-sm font-medium text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 transition-colors"
            >
              Clear Text
            </button>
            <button
              onClick={handleAnalyze}
              disabled={isAnalyzing || text.length < 50}
              className="flex items-center gap-2 bg-slate-900 hover:bg-slate-800 dark:bg-white dark:hover:bg-slate-200 text-white dark:text-slate-900 px-6 py-2.5 rounded-xl font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isAnalyzing ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Scanning Text...
                </>
              ) : (
                <>
                  <Radar className="w-5 h-5" />
                  Scan for AI
                </>
              )}
            </button>
          </div>
        </div>

        {/* RIGHT COMPONENT: Output / Results */}
        <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col items-center justify-center p-8 text-center h-[400px] lg:h-auto">
          {!result && !isAnalyzing && (
            <div className="text-slate-400 dark:text-slate-500 flex flex-col items-center">
              <Radar className="w-16 h-16 opacity-20 mb-4" />
              <h3 className="font-semibold text-lg text-slate-600 dark:text-slate-300">No score yet</h3>
              <p className="text-sm mt-2 max-w-[200px]">Click "Scan for AI" to check your text against our detection models.</p>
            </div>
          )}

          {isAnalyzing && (
            <div className="flex flex-col items-center animate-pulse">
              <div className="relative">
                <Radar className="w-20 h-20 text-blue-500 animate-ping opacity-75" />
                <Radar className="w-20 h-20 text-blue-600 absolute top-0 left-0" />
              </div>
              <h3 className="font-semibold text-lg text-slate-700 dark:text-slate-200 mt-6">Analyzing Patterns...</h3>
              <p className="text-sm text-slate-500 mt-2">Checking perplexity and burstiness.</p>
            </div>
          )}

          {result && !isAnalyzing && (
            <div className="w-full flex flex-col items-center animate-fade-in-up">
              {getScoreIcon(result.score)}
              
              <div className="relative w-48 h-48 flex items-center justify-center">
                {/* Simple Circular Progress representation */}
                <svg className="w-full h-full transform -rotate-90" viewBox="0 0 100 100">
                  <circle
                    className="text-slate-100 dark:text-slate-800"
                    strokeWidth="8"
                    stroke="currentColor"
                    fill="transparent"
                    r="40"
                    cx="50"
                    cy="50"
                  />
                  <circle
                    className={getScoreColor(result.score)}
                    strokeWidth="8"
                    strokeDasharray={251.2}
                    strokeDashoffset={251.2 - (251.2 * result.score) / 100}
                    strokeLinecap="round"
                    stroke="currentColor"
                    fill="transparent"
                    r="40"
                    cx="50"
                    cy="50"
                    style={{ transition: 'stroke-dashoffset 1s ease-in-out' }}
                  />
                </svg>
                <div className="absolute flex flex-col items-center justify-center">
                  <span className={`text-4xl font-bold ${getScoreColor(result.score)}`}>
                    {result.score}%
                  </span>
                  <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider mt-1">AI Score</span>
                </div>
              </div>

              <h3 className={`text-xl font-bold mt-6 ${getScoreColor(result.score)}`}>
                {getScoreLabel(result.score)}
              </h3>
              
              <div className="mt-6 bg-slate-50 dark:bg-slate-800/50 p-4 rounded-xl text-sm text-slate-600 dark:text-slate-300 text-left w-full border border-slate-100 dark:border-slate-800">
                <div className="flex items-center gap-2 font-semibold text-slate-700 dark:text-slate-200 mb-2">
                  <Info className="w-4 h-4" />
                  Detection Analysis
                </div>
                <p className="leading-relaxed">
                  {result.reasoning}
                </p>
              </div>
            </div>
          )}
        </div>

      </div>
    </div>
  )
}
