'use client';

import React, { useState } from 'react';
import {
  Lightbulb, Wrench, FileText, Settings, Type, List, Star, Zap, BarChart,
  Brain, Heart, Layers, Search, Shield, Globe, Database, Code, Users, Target,
  BookOpen, Cpu, Eye, Lock, Trash2, RefreshCw, ArrowRight, ChevronLeft,
  ChevronRight, Sparkles, ArrowRightLeft, CheckCircle
} from 'lucide-react';

/* ─── Icon Mapping ───────────────────────────────────────────── */
const getIcon = (concept: string, size = 28) => {
  const c = (concept || '').toLowerCase();
  const p = { size, strokeWidth: 2 };
  if (c.includes('idea') || c.includes('light')) return <Lightbulb {...p} />;
  if (c.includes('tool') || c.includes('wrench') || c.includes('clean')) return <Wrench {...p} />;
  if (c.includes('file') || c.includes('doc')) return <FileText {...p} />;
  if (c.includes('set') || c.includes('config') || c.includes('gear')) return <Settings {...p} />;
  if (c.includes('text') || c.includes('type') || c.includes('write')) return <Type {...p} />;
  if (c.includes('list')) return <List {...p} />;
  if (c.includes('star') || c.includes('best')) return <Star {...p} />;
  if (c.includes('fast') || c.includes('quick') || c.includes('zap') || c.includes('power')) return <Zap {...p} />;
  if (c.includes('chart') || c.includes('graph') || c.includes('data')) return <BarChart {...p} />;
  if (c.includes('brain') || c.includes('mind') || c.includes('ai') || c.includes('think')) return <Brain {...p} />;
  if (c.includes('heart') || c.includes('love')) return <Heart {...p} />;
  if (c.includes('layer') || c.includes('stack')) return <Layers {...p} />;
  if (c.includes('search') || c.includes('find') || c.includes('seo')) return <Search {...p} />;
  if (c.includes('shield') || c.includes('secure') || c.includes('safe')) return <Shield {...p} />;
  if (c.includes('globe') || c.includes('web') || c.includes('world')) return <Globe {...p} />;
  if (c.includes('database') || c.includes('store') || c.includes('server')) return <Database {...p} />;
  if (c.includes('code') || c.includes('dev')) return <Code {...p} />;
  if (c.includes('user') || c.includes('people') || c.includes('team')) return <Users {...p} />;
  if (c.includes('target') || c.includes('goal')) return <Target {...p} />;
  if (c.includes('book') || c.includes('learn') || c.includes('read')) return <BookOpen {...p} />;
  if (c.includes('cpu') || c.includes('process') || c.includes('compute')) return <Cpu {...p} />;
  if (c.includes('eye') || c.includes('view') || c.includes('vision')) return <Eye {...p} />;
  if (c.includes('lock') || c.includes('private')) return <Lock {...p} />;
  if (c.includes('trash') || c.includes('delete') || c.includes('remove')) return <Trash2 {...p} />;
  if (c.includes('refresh') || c.includes('sync') || c.includes('update')) return <RefreshCw {...p} />;
  return <Target {...p} />;
};

/* ─── Colors ─────────────────────────────────────────────────── */
const accentColors = ['#10b981', '#3b82f6', '#f97316', '#a855f7', '#f43f5e', '#06b6d4', '#eab308', '#8b5cf6'];

/* ─── Shared Slide Wrapper — forces every slide to be full-height ── */
const SlideFrame = ({ children, bg }: { children: React.ReactNode; bg: string }) => (
  <div
    className="w-full flex flex-col justify-center items-center relative overflow-hidden"
    style={{ background: bg, minHeight: '540px', padding: '48px 40px' }}
  >
    {children}
    {/* Watermark */}
    <div className="absolute bottom-3 right-5 flex items-center gap-1 text-[10px] font-medium opacity-30" style={{ color: '#1a3821' }}>
      <Zap size={10} /> Generated by Sovira AI
    </div>
  </div>
);

/* ═══════════════════════════════════════════════════════════════
   SLIDE 1: TITLE
   ═══════════════════════════════════════════════════════════════ */
function TitleSlide({ title, subtitle, totalSlides }: { title: string; subtitle: string; totalSlides: number }) {
  return (
    <SlideFrame bg="linear-gradient(160deg, #c8dbc9 0%, #a8c5ab 50%, #8bb593 100%)">
      <div className="text-center max-w-3xl mx-auto">
        <h1
          className="text-[clamp(2rem,5vw,3.5rem)] font-black leading-[1.15] mb-5"
          style={{ fontFamily: '"Montserrat", "Inter", sans-serif', color: '#1a3821' }}
        >
          {title}
        </h1>
        {subtitle && (
          <p className="text-[clamp(1rem,2vw,1.35rem)] leading-relaxed" style={{ color: '#2d5a3d' }}>
            {subtitle}
          </p>
        )}
        <div className="mt-10 inline-flex items-center gap-2 px-5 py-2 rounded-full text-sm font-semibold" style={{ background: 'rgba(26,56,33,0.12)', color: '#1a3821' }}>
          <Sparkles size={14} /> {totalSlides} slides
        </div>
      </div>
    </SlideFrame>
  );
}

/* ═══════════════════════════════════════════════════════════════
   SLIDE TYPE: CONCEPT  (key points + analogy + pro tip)
   ═══════════════════════════════════════════════════════════════ */
function ConceptSlide({ slide, index }: { slide: any; index: number }) {
  const accent = accentColors[index % accentColors.length];
  return (
    <SlideFrame bg="#f2f6f3">
      {/* Slide number watermark */}
      <div className="absolute top-6 right-8 text-8xl font-black select-none pointer-events-none" style={{ color: '#dbe8dc', fontFamily: '"Montserrat", sans-serif' }}>
        {String(index + 1).padStart(2, '0')}
      </div>

      <div className="w-full max-w-4xl mx-auto">
        {/* Header */}
        <div className="flex items-center gap-4 mb-8">
          <div className="w-14 h-14 rounded-2xl flex items-center justify-center text-white shrink-0" style={{ background: accent, boxShadow: `0 8px 20px ${accent}44` }}>
            {getIcon(slide.icon_concept, 28)}
          </div>
          <h2 className="text-[clamp(1.5rem,3.5vw,2.5rem)] font-extrabold leading-tight" style={{ fontFamily: '"Montserrat", "Inter", sans-serif', color: '#1a3821' }}>
            {slide.title}
          </h2>
        </div>

        {/* Description */}
        <p className="text-lg leading-relaxed mb-8" style={{ color: '#3d5a42', maxWidth: '700px' }}>
          {slide.description}
        </p>

        {/* Key Points */}
        {slide.key_points?.length > 0 && (
          <div className="grid grid-cols-1 gap-3 mb-8">
            {slide.key_points.map((point: string, i: number) => (
              <div key={i} className="flex items-start gap-3 bg-white rounded-xl p-4" style={{ boxShadow: '0 2px 12px rgba(0,0,0,0.06)' }}>
                <CheckCircle size={20} className="shrink-0 mt-0.5" style={{ color: accent }} />
                <span className="text-[15px] leading-relaxed" style={{ color: '#2d3a30' }}>{point}</span>
              </div>
            ))}
          </div>
        )}

        {/* Bottom row: Analogy + Pro Tip */}
        <div className="flex flex-col md:flex-row gap-4">
          {slide.analogy && (
            <div className="flex-1 rounded-xl p-5" style={{ background: '#e8f0e9', borderLeft: '4px solid #7ba884' }}>
              <p className="text-xs font-bold uppercase tracking-wider mb-2" style={{ color: '#5c8564' }}>💡 Analogy</p>
              <p className="text-sm italic leading-relaxed" style={{ color: '#2d3a30' }}>{slide.analogy}</p>
            </div>
          )}
          {slide.pro_tip && (
            <div className="flex-1 rounded-xl p-5 text-white" style={{ background: 'linear-gradient(135deg, #1e3a8a, #3b82f6)', boxShadow: '0 4px 16px rgba(30,58,138,0.25)' }}>
              <p className="text-xs font-bold uppercase tracking-wider mb-2 opacity-80">⚡ Pro Tip</p>
              <p className="text-sm leading-relaxed opacity-95">{slide.pro_tip}</p>
            </div>
          )}
        </div>
      </div>
    </SlideFrame>
  );
}

/* ═══════════════════════════════════════════════════════════════
   SLIDE TYPE: COMPARISON  (left vs right)
   ═══════════════════════════════════════════════════════════════ */
function ComparisonSlide({ slide, index, goldenRule }: { slide: any; index: number; goldenRule?: string }) {
  return (
    <SlideFrame bg="#e8f0e9">
      <div className="absolute top-6 right-8 text-8xl font-black select-none pointer-events-none" style={{ color: '#d0dfd3', fontFamily: '"Montserrat", sans-serif' }}>
        {String(index + 1).padStart(2, '0')}
      </div>

      <div className="w-full max-w-5xl mx-auto flex flex-col items-center justify-center min-h-[450px]">
        {/* Large Centered Title */}
        <h2 className="text-[clamp(2rem,4vw,3rem)] font-extrabold mb-8 text-center leading-tight" style={{ fontFamily: '"Montserrat", "Inter", sans-serif', color: '#1a3821' }}>
          {slide.title}
        </h2>

        {/* Split Screen Design */}
        <div className="flex flex-col md:flex-row items-center justify-between w-full gap-8 md:gap-4 relative">
          
          {/* Left Side */}
          <div className="flex-1 flex flex-col items-center text-center">
            {/* Illustrative Emoji (Concept A) */}
            <div className="text-[120px] leading-none mb-6 drop-shadow-xl select-none filter hover:brightness-110 transition-all duration-300">
              {slide.left_emoji || '🔍'}
            </div>
            
            {/* Bold Subheading */}
            <h3 className="text-2xl font-bold mb-3" style={{ fontFamily: '"Montserrat", sans-serif', color: '#1a3821' }}>
              {slide.left_label || 'Option A'}
            </h3>
            
            {/* Short Description */}
            <p className="text-base" style={{ color: '#3d5a42', maxWidth: '300px' }}>
              {slide.key_points?.[0] || 'Description for this concept.'}
            </p>
          </div>

          {/* Center Directional Arrow (Hand-drawn style) */}
          <div className="hidden md:flex flex-col items-center justify-center shrink-0 w-[120px]">
            <svg width="100" height="60" viewBox="0 0 100 60" fill="none" xmlns="http://www.w3.org/2000/svg" className="opacity-80">
              {/* Curved, organic arrow path */}
              <path d="M5 30 Q 30 -10, 75 30" stroke="#7ba884" strokeWidth="4" fill="none" strokeLinecap="round" />
              <path d="M 60 20 L 78 31 L 62 42" stroke="#7ba884" strokeWidth="4" fill="none" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </div>

          {/* Mobile vs divider */}
          <div className="md:hidden flex items-center justify-center py-4">
             <div className="w-12 h-12 rounded-full flex items-center justify-center text-white" style={{ background: '#1a3821', boxShadow: '0 6px 16px rgba(26,56,33,0.3)' }}>
              <ArrowRightLeft size={20} />
            </div>
          </div>

          {/* Right Side */}
          <div className="flex-1 flex flex-col items-center text-center">
            {/* Illustrative Emoji (Concept B) */}
            <div className="text-[120px] leading-none mb-6 drop-shadow-xl select-none filter hover:brightness-110 transition-all duration-300">
              {slide.right_emoji || '💡'}
            </div>
            
            {/* Bold Subheading */}
            <h3 className="text-2xl font-bold mb-3" style={{ fontFamily: '"Montserrat", sans-serif', color: '#1a3821' }}>
              {slide.right_label || 'Option B'}
            </h3>
            
            {/* Short Description */}
            <p className="text-base" style={{ color: '#3d5a42', maxWidth: '300px' }}>
              {slide.key_points?.[1] || 'Description for this concept.'}
            </p>
          </div>
        </div>

        {/* Pill-shaped Takeaway Banner (Golden Rule) */}
        {(goldenRule || slide.pro_tip) && (
          <div className="mt-14 inline-flex items-center gap-3 px-8 py-3 rounded-full text-white shadow-lg relative z-10" 
               style={{ background: 'linear-gradient(90deg, #3d6b4a, #5c8564)' }}>
            <span className="font-bold text-[#b8d4bd] tracking-wider uppercase text-sm">
              {goldenRule ? 'Golden Rule:' : 'Takeaway:'}
            </span>
            <span className="font-semibold text-[15px]">
              {goldenRule || slide.pro_tip}
            </span>
          </div>
        )}
      </div>
    </SlideFrame>
  );
}

/* ═══════════════════════════════════════════════════════════════
   SLIDE TYPE: LIST  (source → solution rows)
   ═══════════════════════════════════════════════════════════════ */
function ListSlide({ slide, index }: { slide: any; index: number }) {
  const items = slide.items || [];
  return (
    <SlideFrame bg="#e2ece4">
      <div className="absolute top-6 right-8 text-8xl font-black select-none pointer-events-none" style={{ color: '#cddecf', fontFamily: '"Montserrat", sans-serif' }}>
        {String(index + 1).padStart(2, '0')}
      </div>

      <div className="w-full max-w-3xl mx-auto">
        <h2 className="text-[clamp(1.5rem,3.5vw,2.5rem)] font-extrabold mb-3 text-center" style={{ fontFamily: '"Montserrat", "Inter", sans-serif', color: '#1a3821' }}>
          {slide.title}
        </h2>
        {slide.description && <p className="text-center mb-10" style={{ color: '#3d5a42' }}>{slide.description}</p>}

        <div className="space-y-4">
          {items.map((item: any, i: number) => (
            <div key={i} className="flex items-center gap-3">
              {/* Icon */}
              <div className="w-11 h-11 rounded-xl flex items-center justify-center text-white shrink-0"
                style={{ background: accentColors[i % accentColors.length], boxShadow: `0 6px 16px ${accentColors[i % accentColors.length]}33` }}>
                {getIcon(item.icon_concept || 'target', 20)}
              </div>
              {/* Source label */}
              <span className="text-base font-bold shrink-0" style={{ color: '#1a3821', fontFamily: '"Montserrat", sans-serif', minWidth: '130px' }}>
                {item.source}
              </span>
              {/* Dotted line + arrow */}
              <div className="flex-1 relative mx-1" style={{ borderBottom: '2px dashed #8bb593' }}>
                <ArrowRight size={14} className="absolute -right-1 -top-[7px]" style={{ color: '#5c8564' }} />
              </div>
              {/* Solution pill */}
              <div className="px-5 py-2.5 rounded-full text-sm font-bold shrink-0 text-center" style={{ background: '#f0f5f1', border: '1px solid #b8d4bd', color: '#1a3821', minWidth: '140px' }}>
                {item.solution}
              </div>
            </div>
          ))}
        </div>

        {slide.pro_tip && (
          <div className="mt-8 rounded-xl p-5 text-white" style={{ background: 'linear-gradient(135deg, #1e3a8a, #3b82f6)', boxShadow: '0 4px 16px rgba(30,58,138,0.25)' }}>
            <p className="text-xs font-bold uppercase tracking-wider mb-1 opacity-80">⚡ Pro Tip</p>
            <p className="text-sm leading-relaxed opacity-95">{slide.pro_tip}</p>
          </div>
        )}
      </div>
    </SlideFrame>
  );
}

/* ═══════════════════════════════════════════════════════════════
   SLIDE TYPE: PROCESS  (step-by-step flow)
   ═══════════════════════════════════════════════════════════════ */
function ProcessSlide({ slide, index }: { slide: any; index: number }) {
  const items = slide.items || [];
  return (
    <SlideFrame bg="#eef3ef">
      <div className="absolute top-6 right-8 text-8xl font-black select-none pointer-events-none" style={{ color: '#d5e2d7', fontFamily: '"Montserrat", sans-serif' }}>
        {String(index + 1).padStart(2, '0')}
      </div>

      <div className="w-full max-w-4xl mx-auto text-center">
        <h2 className="text-[clamp(1.5rem,3.5vw,2.5rem)] font-extrabold mb-3" style={{ fontFamily: '"Montserrat", "Inter", sans-serif', color: '#1a3821' }}>
          {slide.title}
        </h2>
        {slide.description && <p className="mb-10 mx-auto" style={{ color: '#3d5a42', maxWidth: '600px' }}>{slide.description}</p>}

        <div className="flex flex-col md:flex-row items-center justify-center gap-3 flex-wrap">
          {items.map((item: any, i: number) => (
            <React.Fragment key={i}>
              <div className="bg-white rounded-2xl p-5 text-center" style={{ boxShadow: '0 4px 16px rgba(0,0,0,0.07)', width: '150px' }}>
                <div className="w-12 h-12 rounded-full flex items-center justify-center text-white mx-auto mb-3"
                  style={{ background: accentColors[i % accentColors.length], boxShadow: `0 6px 16px ${accentColors[i % accentColors.length]}33` }}>
                  {getIcon(item.icon_concept || 'zap', 22)}
                </div>
                <p className="text-sm font-bold" style={{ color: '#1a3821', fontFamily: '"Montserrat", sans-serif' }}>{item.source}</p>
                {item.solution && <p className="text-[11px] mt-1" style={{ color: '#5c8564' }}>{item.solution}</p>}
              </div>
              {i < items.length - 1 && <ArrowRight size={22} className="hidden md:block shrink-0" style={{ color: '#7ba884' }} />}
            </React.Fragment>
          ))}
        </div>

        {slide.pro_tip && (
          <div className="mt-8 rounded-xl p-5 text-white text-left mx-auto" style={{ background: 'linear-gradient(135deg, #1e3a8a, #3b82f6)', maxWidth: '500px', boxShadow: '0 4px 16px rgba(30,58,138,0.25)' }}>
            <p className="text-xs font-bold uppercase tracking-wider mb-1 opacity-80">⚡ Pro Tip</p>
            <p className="text-sm leading-relaxed opacity-95">{slide.pro_tip}</p>
          </div>
        )}
      </div>
    </SlideFrame>
  );
}

/* ═══════════════════════════════════════════════════════════════
   SLIDE: GOLDEN RULE (finale)
   ═══════════════════════════════════════════════════════════════ */
function GoldenRuleSlide({ goldenRule }: { goldenRule: string }) {
  return (
    <SlideFrame bg="linear-gradient(160deg, #1a3821, #2d5a3d 60%, #3d6b4a)">
      <div className="text-center max-w-3xl mx-auto">
        <Star className="mx-auto mb-6" size={44} style={{ color: '#fbbf24' }} fill="currentColor" />
        <p className="text-sm font-bold uppercase tracking-[0.25em] mb-6" style={{ color: '#8bb593' }}>
          Golden Rule
        </p>
        <p
          className="text-[clamp(1.5rem,4vw,2.8rem)] font-extrabold leading-tight text-white"
          style={{ fontFamily: '"Montserrat", "Inter", sans-serif' }}
        >
          &ldquo;{goldenRule}&rdquo;
        </p>
      </div>
    </SlideFrame>
  );
}

/* ═══════════════════════════════════════════════════════════════
   MAIN COMPONENT
   ═══════════════════════════════════════════════════════════════ */
export function Infographic({ data }: { data: any }) {
  const [currentSlide, setCurrentSlide] = useState(0);

  /* ─── Normalize ────────────────────────────────── */
  let parsed = { main_title: '', subtitle: '', golden_rule: '', slides: [] as any[] };

  if (Array.isArray(data)) {
    parsed.slides = data.map((s: any) => ({
      slide_type: 'concept', title: s.title || s.key_point || '', icon_concept: s.icon_concept || 'target',
      description: s.description || s.details || '', key_points: s.tags || [],
    }));
    parsed.main_title = 'Generated Infographic';
  } else if (data && typeof data === 'object') {
    parsed.main_title = data.main_title || 'Infographic';
    parsed.subtitle = data.subtitle || '';
    parsed.golden_rule = data.golden_rule || '';
    parsed.slides = Array.isArray(data.slides) ? data.slides
      : Array.isArray(data.sections) ? data.sections.map((s: any) => ({
        slide_type: 'concept', title: s.title || '', icon_concept: s.icon_concept || 'target',
        description: s.description || '', key_points: s.tags || [],
      })) : [];
  }

  const hasGolden = !!parsed.golden_rule;
  const total = 1 + parsed.slides.length + (hasGolden ? 1 : 0);

  const goNext = () => setCurrentSlide(p => Math.min(p + 1, total - 1));
  const goPrev = () => setCurrentSlide(p => Math.max(p - 1, 0));

  const renderSlide = () => {
    if (currentSlide === 0) return <TitleSlide title={parsed.main_title} subtitle={parsed.subtitle} totalSlides={total} />;
    if (hasGolden && currentSlide === total - 1) return <GoldenRuleSlide goldenRule={parsed.golden_rule} />;

    const idx = currentSlide - 1;
    const sl = parsed.slides[idx];
    if (!sl) return null;
    switch (sl.slide_type) {
      case 'comparison': return <ComparisonSlide slide={sl} index={idx} goldenRule={parsed.golden_rule} />;
      case 'list': return <ListSlide slide={sl} index={idx} />;
      case 'process': return <ProcessSlide slide={sl} index={idx} />;
      default: return <ConceptSlide slide={sl} index={idx} />;
    }
  };

  return (
    <div className="w-full max-w-5xl mx-auto rounded-2xl overflow-hidden" data-infographic-total={total} style={{ boxShadow: '0 12px 40px rgba(0,0,0,0.12)' }}>

      {/* Current Slide */}
      <div data-infographic-slide>
        {renderSlide()}
      </div>

      {/* Navigation */}
      <div className="flex items-center justify-between px-5 py-3" style={{ background: '#fff', borderTop: '1px solid #e5ebe6' }}>
        <button onClick={goPrev} disabled={currentSlide === 0}
          className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold transition-all disabled:opacity-25"
          style={{ background: '#eaf2eb', color: '#1a3821' }}>
          <ChevronLeft size={16} /> Prev
        </button>

        {/* Dots */}
        <div className="flex items-center gap-1.5 flex-wrap justify-center">
          {Array.from({ length: total }).map((_, i) => (
            <button key={i} data-infographic-dot onClick={() => setCurrentSlide(i)}
              className="rounded-full transition-all"
              style={{
                width: i === currentSlide ? 24 : 10, height: 10,
                background: i === currentSlide ? '#1a3821' : '#c5d8c7',
              }} />
          ))}
        </div>

        <button onClick={goNext} disabled={currentSlide === total - 1}
          className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold text-white transition-all disabled:opacity-25"
          style={{ background: '#1a3821' }}>
          Next <ChevronRight size={16} />
        </button>
      </div>
    </div>
  );
}
