import { NextResponse } from 'next/server'
import Groq from 'groq-sdk'

// Initialize Groq client
const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY,
})

export async function POST(req: Request) {
  try {
    const { topic, emotion } = await req.json()

    if (!topic) {
      return NextResponse.json({ error: 'Topic or article is required' }, { status: 400 })
    }

    const emotionInstruction = emotion 
      ? `Deliver the script with a strictly ${emotion.toLowerCase()} emotion.`
      : 'Deliver the script in a professional, engaging tone.'

    const prompt = `You are an expert AI podcast scriptwriter.
The user wants to generate a short, highly engaging, solo-speaker podcast segment based on the following topic/article.

Topic/Article:
"""
${topic}
"""

Instructions:
1. Write a captivating, spoken-word podcast script (around 150-250 words).
2. ${emotionInstruction}
3. Start with a hook.
4. Do NOT include any speaker labels, sound effect brackets (like [laugh] or [music]), or stage directions. The output must be PURE text that can be directly read by a Text-to-Speech engine.
5. Use natural conversational pacing, pauses, and rhetorical questions.

Return ONLY the podcast script text. No pleasantries, no markdown.`

    const completion = await groq.chat.completions.create({
      messages: [{ role: 'user', content: prompt }],
      model: 'llama-3.1-8b-instant', // Active fast model for scripting
      temperature: 0.7,
      max_tokens: 1024,
    })

    const script = completion.choices[0]?.message?.content || ''

    if (!script) {
      throw new Error('No script generated by AI')
    }

    return NextResponse.json({ script })
  } catch (error: any) {
    console.error('Podcast Script Generation Error:', error)
    return NextResponse.json({ error: error.message || 'Failed to generate script' }, { status: 500 })
  }
}
